<?php

/**
 * @file
 * Code for the bReol Link paragraph feature.
 */

include_once 'breol_link_paragraph.features.inc';

/**
 * Template preprocessor for entities.
 */
function breol_link_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'breol_linkbox') {
      $wrapper = $variables['paragraphs_item']->wrapper();
      $variables['classes_array'][] = 'linkbox';

      $color = $wrapper->field_breol_linkbox_color->value();
      if (isset($color['rgb'])) {
        $variables['attributes_array']['style'] = 'background-color: ' . $color['rgb'] . ';';
      }

      $variables['icons'] = '';
      $link = $wrapper->field_breol_linkbox_link->value();
      if (isset($link['url'])) {
        $variables['href'] = $link['url'];
        $variables['link_attributes'] =  drupal_attributes($link['attributes'] ?? []);
      }

      $image = $wrapper->field_breol_linkbox_image->value();
      if (isset($image['uri'])) {
        $params = array(
          'style_name' => 'ding_campaign_p_75',
          'path' => $image['uri'],
        );

        // Skip image style for gifs (which we assume are only used for animated gifs).
        $originalImage = '<img src="' . file_create_url($image['uri']) . '"/>';
        $variables['image'] = $image['filemime'] === 'image/gif' ? $originalImage : theme('image_style', $params);

        $variables['classes_array'][] = 'linkbox--with-image';
      }
      if (isset($link['title'])) {
        $variables['title'] = check_plain($link['title']);
      }

      $header = $wrapper->field_breol_linkbox_header->value();

      $variables['header'] = !empty($header) ? check_plain($header) : '';
    }
  }
}

/**
 * Implements hook_paragraphs_item_access().
 *
 * Hide non-web link boxes from web.
 */
function breol_link_paragraph_paragraphs_item_access($entity, $op, $account) {
  if ($entity instanceof ParagraphsItemEntity
    && 'breol_linkbox' === $entity->bundle()
    && 'view' === $op) {
    $wrapper = $entity->wrapper();
    $show_on = $wrapper->field_show_on->value();
    if (!in_array('web', $show_on, TRUE)) {
      return PARAGRAPHS_ITEM_ACCESS_DENY;
    }
  }

  return PARAGRAPHS_ITEM_ACCESS_IGNORE;
}
