<?php

/**
 * @file
 * Code for the BReol News feature.
 */

include_once 'breol_news.features.inc';

/**
 * Implements hook_node_validate().
 */
function breol_news_node_validate($node, $form, &$form_state) {
  if ('breol_news' === $node->type) {
    $field_name = 'field_breol_cover_image';
    $message = reol_base_validate_image_size($node, $field_name);
    if (NULL !== $message) {
      form_set_error($field_name, $message);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Makes the "articles" view show nodes of type "breol_news".
 *
 * The view is defined by the shared "ereol_article" module which has no
 * knowledge of the "breol_news" content type. Therefore we use a hook to
 * alter the view rather than edit the view definition.
 */
function breol_news_views_query_alter(&$view, &$query) {
  if ('articles' === $view->name) {
    foreach ($query->where as &$clause) {
      if (isset($clause['conditions']) && is_array($clause['conditions'])) {
        foreach ($clause['conditions'] as &$condition) {
          if ('node.type' === ($condition['field'] ?? NULL) && 'in' === ($condition['operator'] ?? NULL)) {
            $condition['value'] = ['breol_news'];
          }
        }
      }
    }
  }
}
