<?php

/**
 * @file
 * Base module for ereolen for kids.
 */


/**
 * Implements hook_init().
 */
function breol_base_init() {
  if (module_exists('ding_adgangsplatformen')) {
    drupal_add_js(drupal_get_path('module', 'breol_base') . '/js/breol_base_adgangsplatformen.js', 'file');
  }
}

/**
 * Implements hook_form_alter().
 *
 * Change/remove DDB things from forms.
 */
function breol_base_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'ding_loan_loans_form':
    case 'ding_reservation_reservations_notready_form':
      $form['actions_container']['#access'] = FALSE;
      break;
  }

  $form_ids = array(
    'user_login',
    'user_login_block',
    'ding_user_authenticate_form',
  );

  if (in_array($form_id, $form_ids)) {
    if (module_exists('ding_adgangsplatformen')) {
      $form['adgangsplatformen-wrapper'] = array(
        '#type' => 'fieldset',
        '#description' => t('Log in via adgangsplatformen'),
        '#weight' => 10,
      );

      $form['adgangsplatformen-wrapper']['button'] = array(
        '#attributes' => array(
          'class' => array(
            'adgangsplatformen-button',
          ),
        ),
        '#type' => 'link',
        '#href' => DING_ADGANGSPLATFORMEN_LOGIN_URL,
        '#title' => t('Login'),
        '#options' => array('html' => TRUE),
        '#prefix' => '<div class="adgangsplatformen-wrapper">',
        '#suffix' => '</div>',
      );
    }
  }
}

/**
 * Implements hook_ajax_login_command().
 *
 * This is an hack to get around the fact that we need adgangsplatformen to
 * hijack ajax login url's, but on eReolenGo we need the normal login to be
 * shown first to give the option to use uni-login or adgangsplatformen. This
 * hook is part of the ding_user SSO solution from DDB Core - a little mis-used
 * here.
 */
function breol_base_ajax_login_command($path) {
  if (module_exists('ding_adgangsplatformen')) {
    $form_state = array();
    $form = drupal_build_form('user_login', $form_state);
    $login_form = drupal_render($form);

    return ajax_command_ding_popup('ding_user', t('Login'), $login_form, array('resubmit' => TRUE));
  }
}

/**
 * Implements hook_field_default_field_instances_alter().
 */
function breol_base_field_default_field_instances_alter(&$fields) {
  if (isset($fields['ting_object-ting_object-ting_details_language'])) {
    // Show language in "compact" view.
    $fields['ting_object-ting_object-ting_details_language']['display']['compact'] = [
      'label' => 'hidden',
      'module' => 'ting_material_details',
      'settings' => array(),
      'type' => 'ting_details_single',
      'weight' => 1,
    ];
  }

  // Move cover before details_language.
  if (isset($fields['ting_object-ting_object-ting_cover'])) {
    $fields['ting_object-ting_object-ting_cover']['display']['compact']['weight'] = 0;
  }

  // Show language in "search_result" view (moved into group by
  // `breol_base_field_default_field_instances_alter`, which see).
  $fields['ting_object-ting_object-ting_details_language']['display']['search_result'] = [
    'label' => 'hidden',
    'module' => 'ting_material_details',
    'settings' => array(),
    'type' => 'ting_details_single',
    'weight' => 2,
  ];

  // Hide material type.
  if (isset($fields['ting_object-ting_object-ting_details_type'])) {
    $fields['ting_object-ting_object-ting_details_type']['display']['compact'] = [
      'label' => 'hidden',
      'module' => 'ting_material_details',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 6,
    ];
  }
}

/**
 * Implements hook_field_group_info_alter().
 */
function breol_base_field_group_info_alter(&$groups) {
  // Move group after language field.
  if (isset($groups['group_overlay|ting_object|ting_object|compact'])) {
    $groups['group_overlay|ting_object|ting_object|compact']->data['weight'] = 2;
  }

  // Move language into group.
  if (isset($groups['group_ting_left_col_search|ting_object|ting_object|search_result']->data['children'])) {
    $groups['group_ting_left_col_search|ting_object|ting_object|search_result']->data['children'] = [
      'ting_cover',
      'ting_details_language',
    ];
  }
}
