<?php

/**
 * @file
 * Module file for breol_app_warning.
 */

/**
 * Implements hook_menu().
 */
function breol_app_warning_menu() {
  $items['admin/config/ereolen/breol_app_warning'] = [
    'title' => 'App warning settings',
    'description' => 'Settings for the app warning',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['breol_app_warning_admin_form'],
    'access arguments' => ['administer site configuration'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/breol_app_warning.admin.inc',
  ];

  return $items;
}

/**
 * Implements hook_init().
 */
function breol_app_warning_init() {
  if (drupal_is_front_page() && isset($_SERVER['HTTP_USER_AGENT'])) {
    $user_agent = $_SERVER['HTTP_USER_AGENT'];
    $pattern = variable_get('breol_app_warning_popup_user_agent_pattern');
    $title = variable_get('breol_app_warning_popup_title');
    $content = variable_get('breol_app_warning_popup_content');

    if ($pattern && $title && $content && @preg_match($pattern, $user_agent)) {
      // We don't want to cache the page with the popup.
      // @TODO Do we actually need to do this? Can we do it in a better way?
      drupal_page_is_cacheable(FALSE);

      $response = [
        'title' => $title,
        'data' => $content,
        'name' => 'app_warning',
        'class' => ['app-warning'],
        'extra_data' => (object)[],
      ];

      drupal_add_css(drupal_get_path('module', 'breol_app_warning') . '/css/dialog.css');
      // Required by ding_popup.
      drupal_add_library('system', 'ui.dialog');
      drupal_add_js('jQuery(function() { Drupal.ding_popup.open('.json_encode($response).') })', 'inline');
    }
  }
}
