<?php

/**
 * @file
 * Code for the BReol inspiration feature.
 */

include_once 'breol_inspiration.features.inc';

/**
 * Implements hook_node_validate().
 */
function breol_inspiration_node_validate($node, $form, &$form_state) {
  if ('inspiration' === $node->type) {
    $field_name = 'field_app_feed_image';
    $message = reol_base_validate_image_size($node, $field_name);

    if (NULL !== $message) {
      form_set_error($field_name, $message);
    }
  }
}

/**
 * Implements hook_field_default_field_bases_alter().
 *
 * Make sure that we can pick news in news carousels.
 */
function breol_inspiration_field_default_field_bases_alter(&$fields) {
  if (isset($fields['field_picked_articles'])) {
    $fields['field_picked_articles']['settings']['handler_settings']['target_bundles'] = ['breol_news' => 'breol_news'];
  }
}

/**
 * Implements hook_paragraphs_item_access().
 */
function ereol_inspiration_paragraphs_item_access(ParagraphsItemEntity $entity, string $op, $account) {
  // Deny view access to blue titles info paragraphs.
  return ('view' === $op && 'blue_titles_info' === $entity->bundle()) ? PARAGRAPHS_ITEM_ACCESS_DENY : PARAGRAPHS_ITEM_ACCESS_IGNORE;
}
