<?php

/**
 * @file
 * Allows users to log in via Unilogin.
 */

use Drupal\ding_unilogin\ApiRouter;
use Drupal\ding_unilogin\Exception\HttpException;
use Drupal\ding_unilogin\Router;
use Drupal\ding_unilogin\UniloginHelper;

define('DING_UNILOGIN_LOGIN_PATH', 'unilogin/login');
define('DING_UNILOGIN_REDIRECT_PATH', 'unilogin/callback');

/**
 * Implements hook_init().
 *
 * Handle Unilogin and add javascript settings.
 *
 * Monkeypatch AJAX to make a note of the popup triggered, in case we need to
 * re-trigger it later (after logging in via Unilogin).
 */
function ding_unilogin_init() {
  // Authenticated users with no "update" access to errors paths should be
  // redirected to the error redirect path.
  if (user_is_logged_in()) {
    global $user;
    $node = menu_get_object();
    if (!$node || !node_access('update', $node, $user)) {
      $path = current_path();
      $patterns = variable_get('ding_unilogin_error_paths', '');
      $redirect_path = variable_get('ding_unilogin_error_paths_redirect_path', 'user');
      if ($redirect_path !== $path && drupal_match_path($path, $patterns)) {
        drupal_goto($redirect_path);
      }
    }
  }

  drupal_add_js(drupal_get_path('module', 'ding_unilogin') . '/js/ding_unilogin_monkeypatch.js', 'file');
}

/**
 * Implements hook_menu().
 */
function ding_unilogin_menu() {
  $items = array();

  // Administration config page.
  $items['admin/config/ding/unilogin'] = array(
    'title' => 'Unilogin access',
    'description' => 'Configure Unilogin access',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_unilogin_admin_settings_form'),
    'access arguments' => array('configure unilogin'),
    'file' => 'includes/ding_unilogin.admin.inc',
  );

  $items['admin/config/ding/unilogin_institutions'] = array(
    'title' => 'Unilogin institutions',
    'description' => 'Configure Unilogin institutions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_unilogin_admin_institutions_form'),
    'access arguments' => array('configure unilogin'),
    'file' => 'includes/ding_unilogin.admin.inc',
  );

  $items['admin/config/ding/unilogin_nonstitutions'] = array(
    'title' => 'Unilogin nonstitutions',
    'description' => 'Configure Unilogin institutions that are missing municipality data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_unilogin_admin_nonstitutions_form'),
    'access arguments' => array('configure unilogin'),
    'file' => 'includes/ding_unilogin.admin.inc',
  );

  $items['admin/config/ding/unilogin_api'] = array(
    'title' => 'Unilogin api',
    'description' => 'Configure Unilogin api',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_unilogin_admin_api_form'),
    'access arguments' => array('configure unilogin'),
    'file' => 'includes/ding_unilogin.admin.inc',
  );

  $items['unilogin/api/%'] = array(
    'page callback' => 'ding_unilogin_api_router',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'delivery callback' => 'ding_unilogin_jsonapi_deliver',
  );

  $items[DING_UNILOGIN_LOGIN_PATH] = array(
    'title' => 'Log in',
    'page callback' => 'ding_unilogin_login',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );

  $items[DING_UNILOGIN_REDIRECT_PATH] = array(
    'page callback' => 'ding_unilogin_callback',
    // Shouldn't have access control.
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['unilogin/%'] = array(
    'page callback' => 'ding_unilogin_router',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_page_alter().
 *
 * This is a hack to reload user pages when user presses the back button. When
 * logging out of Unilogin, the user is left at a dead end, and might use the
 * back button to get back to us. Per default this means they'll end up at the
 * user profile page, apparently still logged in, which is confusing.
 *
 * The problem is that the page is loaded from the bfcache (back-forward cache),
 * which ignores any cache busting headers of the page (which is according to
 * spec, as the history is supposed to show you what you saw).
 *
 * Ideally, Unilogin should provide a link back to us, but that's not likely to
 * happen any time soon.
 *
 * One is supposed to use the pageshow JS event, however, Chrome has a bug where
 * the event object doesn't have the right persisted value, which is the one
 * that allows us to detect if we're loading from cache or not, so that's not
 * much use.
 *
 * So instead we're relying on the fact that non-JS-created input elements are
 * not reset to their default value when reloading the page from bfcache.
 */
function ding_unilogin_page_alter(&$page) {
  if (arg(0) == 'user') {
    $script = "jQuery(document).ready(function() {
  var e = jQuery('#ding_unilogin_hidden');
  if (e.val() == 'not_from_history') {
    e.val('from_history');
  }
  else {
    e.val('not_from_history');
    // Clear out page while loading.
    jQuery('body').empty();
    window.location.reload(true);
  }
});
";

    $page['content']['ding_unilogin_hidden'] = array(
      '#markup' => '<input id="ding_unilogin_hidden" type="hidden" name="ding_unilogin_hidden" value="not_from_history" />',
      '#attached' => array(
        'js' => array(
          array(
            'data' => $script,
            'type' => 'inline',
            'scope' => 'header',
          ),
        ),
      ),
    );
  }
}

/**
 * Implements hook_permission().
 */
function ding_unilogin_permission() {
  return array(
    'configure unilogin' => array(
      'title' => t('Configure Unilogin'),
      'description' => t('Allow role to configure Unilogin settings.'),
    ),
  );
}

/**
 * Alter the login form.
 *
 * Add in link for logging in via Unilogin.
 *
 * @param array $form
 *   The form array to alter.
 * @param array $form_state
 *   The state of the form.
 */
function ding_unilogin_form_alter(array &$form, array &$form_state, $form_id) {
  $form_ids = array(
    'user_login',
    'user_login_block',
    'ding_user_authenticate_form',
  );

  if (in_array($form_id, $form_ids)) {
    if (variable_get('ding_unilogin_id', '')) {
      $form['unilogin_wrapper'] = array(
        '#type' => 'fieldset',
        '#description' => t('Log in via !service', array('!service' => '<span class="unilogin-logo">Unilogin</span>')),
        '#weight' => -10,
      );

      $form['unilogin_wrapper']['unilogin'] = array(
        '#attributes' => array(
          'class' => array(
            'unilogin-button',
          ),
        ),
        '#type' => 'link',
        '#href' => DING_UNILOGIN_LOGIN_PATH,
        // Attach our JavaScript to set the path from which login is initiated.
        '#attached' => array(
          'js' => array(
            drupal_get_path('module', 'ding_unilogin') . '/js/ding_unilogin.js',
          ),
        ),
        '#title' => t('Login'),
        '#prefix' => '<div class="unilogin-wrapper">',
        '#suffix' => '</div>',
      );
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for profile2_form().
 *
 * Hide the pincode change widget for Unilogin users. This modules weight
 * ensures we get called after ding_user_form_profile2_form_alter().
 */
function ding_unilogin_form_profile2_form_alter(&$form, &$form_state) {
  if (ding_unilogin_authenticated()) {
    if (isset($form['pass'])) {
      $form['pass']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_user_logout().
 */
function ding_unilogin_user_logout($account) {
  if (variable_get('ding_unilogin_global_logout', FALSE) && ding_unilogin_authenticated($account)) {
    try {
      _ding_unilogin_get_unilogin_helper()->getProvider()->endSession(
        url('<front>', ['absolute' => TRUE]),
        $_SESSION['oauth2access_token_values']['id_token'] ?? ''
      );
      unset($_SESSION['oauth2access_token_values']);
      drupal_set_message(t('Succesfully logged out of Unilogin'));
    }
    catch (\Exception $e) {
      drupal_set_message(t('Error logging out of Unilogin'), 'error');
      watchdog_exception('ding_unilogin', $e, NULL, array(), WATCHDOG_ERROR);
    }
  }
  _ding_unilogin_set_user_data(NULL);
}

/**
 * Implements hook_publizon_client_id_alter().
 *
 * Change Publizon client id for Unilogin users.
 */
function ding_unilogin_publizon_client_id_alter(&$client_id) {
  if (_ding_unilogin_in_progress() || ding_unilogin_authenticated()) {
    $client_id = variable_get('ding_unilogin_publizon_client_id', '');
  }
}

/**
 * Check whether a user is logged in via Unilogin.
 *
 * @param mixed $account
 *   TODO Missing parameter comment.
 *
 * @return bool
 *   TRUE if authenticated with unilogin else FALSE.
 */
function ding_unilogin_authenticated($account = NULL) {
  global $user;
  if (!$account) {
    $account = $user;
  }

  return isset($account->data['unilogin']) && $account->data['unilogin'];
}

/**
 * Attempt to log in Unilogin user.
 *
 * @param string $username
 *   The Unilogin user name.
 *
 * @return bool
 *   Whether the user was logged in.
 *
 * @throws \DingProviderDoesntImplement
 * @throws \DingProviderNoProvider
 */
function _ding_unilogin_login($username) {
  _ding_unilogin_in_progress(TRUE);
  // If we reach this code a Unilogin user has been authenticated and has
  // access to eReolen GO!.
  $access = TRUE;
  $unilogin_data = [];

  try {
    $user = new DingUniloginUser(
      $username,
      variable_get('ding_unilogin_ws_user', ''),
      variable_get('ding_unilogin_ws_pass', '')
    );
    $user->setAuthName(ding_user_default_authname($username));

    foreach (module_implements('ding_unilogin_login') as $module) {
      $access = module_invoke($module, 'ding_unilogin_login', $user);
      // Break out if someone denied access.
      if (!$access) {
        break;
      }
    }

    if ($access) {
      $institutionIds = $user->getInstitutionsIds();
      $municipalities = $user->getInstitutionMunicipalities($institutionIds);
      $institutions = $user->getInstitutions() ?: [];
      $unilogin_data['institutions'] = $institutions;

      // Get retailer id from first institution.
      $municipalityIds = !empty($institutions) ? [reset($institutions)->kommunenr] : [];
      $libraries = publizon_filter_libraries_list($municipalityIds, 'unilogin');
      if (!empty($libraries)) {
        // Take the first one.
        $library = reset($libraries);
      }
      else {
        watchdog('publizon', 'Unilogin municipalities @municipalities not configured on any library', array('@municipalities' => implode(', ', $municipalities)), WATCHDOG_NOTICE);
        $access = FALSE;
      }
    }
  }
  catch (Exception $e) {
    drupal_set_message(t('Sorry, but there was problems while communicating with Unilogin. Please try again later.'));
    watchdog_exception('ding_unilogin', $e, NULL, array(), WATCHDOG_ERROR);
    _ding_unilogin_in_progress(FALSE);
    return FALSE;
  }

  if (!$access) {
    drupal_set_message(t('Sorry, but that Unilogin account has not been granted access. Please contact the administrator if you think this is wrong.'), 'error');
    watchdog('ding_unilogin', 'Access denied for Unilogin user %user', array('%user' => $username), WATCHDOG_NOTICE);
    _ding_unilogin_in_progress(FALSE);
    return FALSE;
  }

  $success = FALSE;
  try {
    $account = ding_user_authenticate(array(
      'name' =>  $user->getName(),
      'pass' => '',
      'extra' => array(
        'attributes' => array(
          'unilogin' => $library->unilogin_id,
        )),
      'single_sign_on' => TRUE
    ));

    if ($account !== FALSE) {
      global $user;
      $user = $account;

      // Ensure that the user hooks are called.
      user_login_finalize();

      // Make a note that this is a Unilogin account in data by saving once more.
      user_save($account, array('data' => array('unilogin' => TRUE)));
      _ding_unilogin_set_user_data($unilogin_data);

      $success = TRUE;
    }
  }
  catch (Exception $exception) {
    // Exception thrown, log error and carry on.
    watchdog_exception('ding_user', $exception);
    drupal_set_message(t('Unknown error. Please contact the library for help'));

    _ding_unilogin_in_progress(FALSE);
  }

  return $success;
}

/**
 * Get a Unilogin service.
 *
 * @param string $service
 *   The service to get, either 'auth', 'user' or 'inst'.
 *
 * @return \DingUniloginWSIautor|\DingUniloginWSIbruger|\DingUniloginWSIinst
 *   Service object.
 */
function ding_unilogin_wservice($service) {
  switch ($service) {
    case 'auth':
      return new DingUniloginWSIautor(
        variable_get('ding_unilogin_ws_user', ''),
        variable_get('ding_unilogin_ws_pass', '')
      );

    case 'user':
      return new DingUniloginWSIbruger(
        variable_get('ding_unilogin_ws_user', ''),
        variable_get('ding_unilogin_ws_pass', '')
      );

    case 'inst':
      return new DingUniloginWSIinst(
        variable_get('ding_unilogin_ws_user', ''),
        variable_get('ding_unilogin_ws_pass', '')
      );

    default:
      throw new RuntimeException('Bad service type ' . $service);
  }
}

/**
 * Whether we're in the process of logging in a Unilogin user.
 *
 * We need to be able to determine whether we're in the process of logging in an
 * Unilogin user, in order to change the Publizon client id for the
 * authentication request.
 *
 * @param bool|null $new_state
 *   New progress state, if not null.
 *
 * @return bool
 *   Whether we're in progress or not.
 */
function _ding_unilogin_in_progress($new_state = NULL) {
  $state = &drupal_static('__FUNCTION__', FALSE);

  if (!is_null($new_state)) {
    $state = $new_state;
  }

  return $state;
}

/**
 * Implements hook_theme().
 */
function ding_unilogin_theme() {
  return array(
    'ding_unilogin_admin_institutions_form' => array(
      'render element' => 'form',
    ),
    'ding_unilogin_admin_nonstitutions_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Filter institution numbers if requested.
 *
 * @param array $institution_ids
 *   The institution ids.
 *
 * @return array
 *   The filtered institution ids.
 */
function ding_unilogin_filter_institutions(array $institution_ids) {
  if (variable_get('ding_unilogin_institutions_apply_filter', FALSE)) {
    $institutions = _ding_unilogin_get_institutions();
    $institution_ids = array_filter($institution_ids, static function ($institution_id) use ($institutions) {
      return isset($institutions[$institution_id]);
    });
  }

  return $institution_ids;
}

/**
 * Get Unilogin user data.
 *
 * @return null|array
 *   The previously stored user data if any.
 */
function ding_unilogin_get_user_data() {
  return $_SESSION['ding_unilogin_user_data'] ?? NULL;
}

/**
 * Set Unilogin user data.
 *
 * @param null|array $data
 *   The data to store or NULL to clear the user data.
 */
function _ding_unilogin_set_user_data(array $data = NULL) {
  if (NULL === $data) {
    unset($_SESSION['ding_unilogin_user_data']);
  }
  else {
    $_SESSION['ding_unilogin_user_data'] = $data;
  }
}

/**
 * Get Unilogin institutions.
 *
 * @param bool $with_municipalities
 *   If true, municipality data will be added to each institution.
 *
 * @return array
 *   The list of institutions indexed by id.
 */
function _ding_unilogin_get_institutions($with_municipalities = FALSE) {
  $institutions = variable_get('ding_unilogin_institutions', []);

  if ($with_municipalities) {
    // Add information on municipalities.
    $municipalities = _ding_unilogin_get_municipalities();
    foreach ($institutions as &$institution) {
      $institution['municipality'] = $municipalities[$institution['id']] ?? NULL;
    }
  }

  return $institutions;
}

/**
 * Set Unilogin institutions.
 *
 * @param array $institutions
 *   The list of institutions indexed by id.
 */
function _ding_unilogin_set_institutions(array $institutions) {
  // Force institution ids to be strings (most look like integers).
  foreach ($institutions as &$institution) {
    $institution['id'] = (string) $institution['id'];
  }
  variable_set('ding_unilogin_institutions', $institutions);

  _ding_unilogin_update_municipalities(array_keys($institutions));
}

/**
 * Get Unilogin nonstitutions.
 *
 * @return array
 *   The list of nonstitutions indexed by id.
 */
function _ding_unilogin_get_nonstitutions() {
  return variable_get('ding_unilogin_nonstitutions', []);
}

/**
 * Get Unilogin nonstitution municipality data.
 *
 * @return array
 *   The list of municipalities indexed by institution id.
 */
function _ding_unilogin_get_nonstitution_municipalities() {
  return array_map(static function (array $data) {
    $municipality = [];
    foreach ($data as $key => $value) {
      if (preg_match('/^municipality_(?P<key>.+)$/', $key, $matches)) {
        $municipality[$matches['key']] = $value;
      }
    }

    return $municipality;
  }, _ding_unilogin_get_nonstitutions());
}

/**
 * Set Unilogin nonstitutions.
 *
 * @param array $nonstitutions
 *   The list of nonstitutions indexed by id.
 */
function _ding_unilogin_set_nonstitutions(array $nonstitutions) {
  variable_set('ding_unilogin_nonstitutions', $nonstitutions);
}

/**
 * Update Unilogin municipalities.
 *
 * @param array $institution_ids
 *   The list of institution ids.
 */
function _ding_unilogin_update_municipalities(array $institution_ids = NULL) {
  if (NULL === $institution_ids) {
    $institution_ids = array_keys(_ding_unilogin_get_institutions());
  }

  /** @var \DingUniloginWSIinst $service */
  $service = ding_unilogin_wservice('inst');
  $municipalities = $service->getInstitutions($institution_ids);

  // Index by institution id.
  $municipalities = array_column($municipalities, NULL, 'instnr');

  variable_set('ding_unilogin_municipalities', $municipalities);
}

/**
 * Get Unilogin municipalities.
 *
 * @return array
 *   The list of municipalities id.
 */
function _ding_unilogin_get_municipalities() {
  $municipalities = variable_get('ding_unilogin_municipalities', []);

  // Merge in additional municipality data from nonstitutions.
  $nonstitution_municipalities = _ding_unilogin_get_nonstitution_municipalities();
  foreach ($municipalities as &$municipality) {
    $institution_id = $municipality->instnr;
    if (isset($nonstitution_municipalities[$institution_id])) {
      foreach ($nonstitution_municipalities[$institution_id] as $key => $value) {
        if (!empty($value)) {
          $municipality->{$key} = $value;
        }
      }
    }
  }

  return $municipalities;
}

/**
 * Router.
 *
 * @return array|\Exception
 *   The data on success or an exception.
 */
function ding_unilogin_router() {
  $args = func_get_args();

  try {
    $router = new Router();

    return $router->route($args);
  }
  catch (\Exception $exception) {
    return [
      '#markup' => $exception->getMessage(),
    ];
  }
}

/**
 * Api router.
 *
 * @return array|\Exception
 *   The data on success or an exception.
 */
function ding_unilogin_api_router() {
  $args = func_get_args();

  try {
    $router = new ApiRouter();
    $result = $router->route($args);

    return $result;
  }
  catch (\Exception $exception) {
    return $exception;
  }
}

/**
 * Deliver data in the JSON:API format (https://jsonapi.org/format/).
 *
 * @param null|array|\Exception $result
 *   The result to return.
 */
function ding_unilogin_jsonapi_deliver($result = NULL) {
  drupal_add_http_header('content-type', 'application/vnd.api+json');

  $http_origin = $_SERVER['HTTP_ORIGIN'] ?? NULL;
  if (_ding_unilogin_is_allowed_http_origin($http_origin)) {
    // Set Cross-Origin Resource Sharing headers
    // (cf. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
    // @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
    drupal_add_http_header('access-control-allow-origin', $http_origin);
    // Allow our custom authorization header.
    // @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
    drupal_add_http_header('access-control-allow-headers', implode(',', ['x-authorization', 'content-type']));
  }

  drupal_page_is_cacheable(FALSE);

  if ($result instanceof \Exception) {
    if ($result instanceof HttpException) {
      drupal_add_http_header('status', $result->getStatusHeader());
    }
    $result = array(
      // @see https://jsonapi.org/format/#error-objects.
      'errors' => array(
        array(
          'title' => $result->getMessage(),
          'code' => $result->getCode(),
        ),
      ),
    );
  }

  if (NULL === $result) {
    drupal_add_http_header('status', '204 No Content');
    exit;
  }

  echo drupal_json_encode($result);
}

/**
 * Check if http origin is allowed.
 *
 * @param string|null $http_origin
 *   The http origin.
 *
 * @return bool
 *   True if and only if http origin is set and allowed.
 */
function _ding_unilogin_is_allowed_http_origin($http_origin) {
  if (empty($http_origin)) {
    return FALSE;
  }

  $spec = variable_get('ding_unilogin_api_allowed_http_origins');
  $allowed_http_origins = array_map('trim', explode(PHP_EOL, $spec));

  return in_array($http_origin, $allowed_http_origins, TRUE);
}

/**
 * Get user data from UNI-Login service.
 *
 * On success, the result will have the following keys:
 *
 *   "username": the username
 *   "municipality": data on the user's municipality
 *   "library": data on the user's library
 *
 * @param string $username
 *   The username.
 *
 * @return array
 *   The user data.
 */
function _ding_unilogin_get_data($username) {
  $user = new DingUniloginUser(
    $username,
    variable_get('ding_unilogin_ws_user', ''),
    variable_get('ding_unilogin_ws_pass', '')
  );
  $user->setAuthName(ding_user_default_authname($username));

  foreach (module_implements('ding_unilogin_login') as $module) {
    $access = module_invoke($module, 'ding_unilogin_login', $user);
    // Break out if someone denied access.
    if (!$access) {
      throw new RuntimeException('User does not have access.');
    }
  }

  $institutionIds = $user->getInstitutionsIds();
  // Called for side-effects!
  $user->getInstitutionMunicipalities($institutionIds);
  $institutions = $user->getInstitutions() ?: [];

  // Always use first institution.
  $institution = reset($institutions);
  if (empty($institution)) {
    throw new RuntimeException('Cannot get institution');
  }

  // Get library.
  $municipalityIds = [$institution->kommunenr];
  $libraries = publizon_filter_libraries_list($municipalityIds);
  $library = reset($libraries);
  if (empty($library)) {
    throw new RuntimeException('Missing library');
  }

  // Get institution with municipality.
  $institutions = _ding_unilogin_get_institutions(TRUE);
  $institution = $institutions[$institution->instnr] ?? NULL;
  if (empty($institution)) {
    throw new RuntimeException('Cannot get institution');
  }

  return [
    'username' => $user->getName(),
    'institution' => $institution,
    'library' => [
      'name' => $library->library_name,
      'retailer_id' => $library->retailer_id,
      'unilogin_id' => $library->unilogin_id,
    ],
  ];
}

/**
 * Login menu callback.
 */
function ding_unilogin_login() {
  ding_user_set_destination($_GET['path'] ?? 'user/me');

  $url = _ding_unilogin_get_unilogin_helper()->generateLoginUrl();

  // Redirect the user to the authorization URL. We don't use drupal_goto as it
  // looks into the destination in the current URL and preforms some magic with
  // it that we don't want.
  header('Location:' . $url);
  drupal_exit($url);
}

/**
 * Redirect URI callback.
 *
 * This is the end-point used when coming back from the unilogin login
 * and this will try to log the user into the provider and Drupal.
 */
function ding_unilogin_callback() {
  $destination = ding_user_get_destination();
  if (isset($_GET['error'])) {
    drupal_set_message($_GET['error'] . '<br/>' . ($_GET['error_description']), 'error');
    _ding_unilogin_redirect_user();
  }

  if (empty($_GET['state']) || empty($_SESSION['oauth2state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {
    unset($_SESSION['oauth2state']);
    unset($_SESSION['oauth2ajax']);

    drupal_set_message(t('Invalid state detected. Login failed.'));
    _ding_unilogin_redirect_user();
  }
  else {
    if (empty($_SESSION['oauth2code_verifier'])) {
      drupal_set_message(t('Invalid state detected. Login failed.'));
      _ding_unilogin_redirect_user();
    }

    try {
      // Try to get an access token using the authorization code grant.
      $provider = _ding_unilogin_get_unilogin_helper()->getProvider();
      $access_token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code'],
        'code_verifier' => $_SESSION['oauth2code_verifier'],
      ]);
      unset($_SESSION['oauth2code_verifier']);

      // Store access tokens values for later usage, e.g. whe ending Unilogin
      // session.
      $_SESSION['oauth2access_token_values'] = $access_token->getValues();

      $user_info = $provider->introspectToken($access_token);

      if ($username = $user_info['uniid'] ?? NULL) {
        $success = _ding_unilogin_login($username);

        $info = drupal_parse_url($destination ?? '');
        // Trying to make less load during morning login, by redirecting users
        // from the frontpage to the user page as this is the default pattern
        // observed.
        $path = rtrim($info['path'], '/') ?: '/user/me';

        drupal_goto($path, ['query' => $info['query'] ?? []]);
      }

      drupal_set_message(t('Cannot get Unilogin user ID'), 'error');
      _ding_unilogin_redirect_user();
    }
    catch (IdentityProviderException $e) {
      // Failed to get the access token or user details.
      watchdog_exception('ding_unilogin', $e);

      drupal_set_message(t('Failed to login and get user details for the user.'), 'warning');

      // Clean up session variables to prevent redirects loop.
      unset($_SESSION['oauth2access_token_values']);
      unset($_SESSION['oauth2state']);

      // Redirect user back.
      _ding_unilogin_redirect_user();
    }
  }
}

/**
 * Redirect the user.
 *
 * If destination exists in the current session the user is redirect to it, else
 * they are redirected to their profile page.
 *
 * @param string $url
 *   The url to redirect to if destination is not set in the request. Defaults
 *   to /user.
 */
function _ding_unilogin_redirect_user($url = 'user') {
  if (!is_null(ding_user_get_destination())) {
    $url = ding_user_get_destination();
    ding_user_set_destination(NULL);
  }

  // The redirect url may contain query parameters from tracking etc. but this
  // be encoded in drupal_goto below, so we need to split it into an query
  // option.
  $info = drupal_parse_url($url);
  drupal_goto($info['path'], ['query' => $info['query'] ?? []]);
}

/**
 * Get Unilogin helper.
 *
 * @return \Drupal\ding_unilogin\UniloginHelper
 *   The Unilogin helper.
 */
function _ding_unilogin_get_unilogin_helper() {
  $helper = &drupal_static(__FUNCTION__);
  if (!isset($helper)) {
    $helper = new UniloginHelper();
  }

  return $helper;
}
